apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - namespace.yaml
  - central.yaml
  - sa-create-cluster-init-bundle.yaml
  - job-create-cluster-init-bundle.yaml
  - job-patch-internal-registry-creds.yaml
