apiVersion: batch/v1
kind: Job
metadata:
  name: transform-builder-secret
  namespace: superheroes-build
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              # Extract the builder SA login details from the existing secret
              #BUILDER_LOGIN=$(oc get secret $(oc get secrets | awk '/builder-dockercfg/ {print $1}') -ojson | jq -r '.data.".dockercfg"'  | base64 -d)
              # No jq so use python!
              BUILDER_LOGIN=$(oc get secret $(oc get secrets | awk '/builder-dockercfg/ {print $1}') -ojson | python3 -c "import sys, json; print(json.load(sys.stdin)['data'])" | awk '{print $NF}' | sed 's/.$//')

              # Generate the new 'internal-registry' secret
              cat > /tmp/secret-internal-registry.yaml <<__EOL
              apiVersion: v1
              kind: Secret
              metadata:
                name: internal-registry
              stringData:
              __EOL
              echo -n "  config.json: $BUILDER_LOGIN" >> /tmp/secret-internal-registry.yaml
 
              # Apply the new secret
              oc apply -f  /tmp/secret-internal-registry.yaml
          imagePullPolicy: Always
          name: transform-builder-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: transform-secrets
      serviceAccountName: transform-secrets
      terminationGracePeriodSeconds: 30
