apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-deploytotest
  labels:
    app.kubernetes.io/instance: tekton
spec:
  params:
    - description: 'The ChangeID in the Change Management System'
      name: change-id
      type: string
    - name: commit-id
      type: string
    - name: config-repo-url
      type: string
      default: 'https://github.com/redhat-cbr/superheroes-cicd.git'
    - name: source-repo-url
      type: string
      default: 'https://github.com/redhat-cbr/quarkus-super-heroes.git'
    - name: images
      type: string
#    - name: cluster-url
#      type: string
#      default: 'cluster-gm4nw.gm4nw.sandbox3016.opentlc.com'
  tasks:
    - name: debug-input
      params:
        - name: change-id
          value: $(params.change-id)
        - name: commit-id
          value: $(params.commit-id)
        - name: config-repo-url
          value: $(params.config-repo-url)
        - name: source-repo-url
          value: $(params.source-repo-url)
        - name: images
          value: $(params.images)
      taskRef:
        kind: Task
        name: debug-input
    - name: clone-config-repo
      runAfter:
        - debug-input
      taskRef: 
        name: git-clone
        kind: ClusterTask 
      params: 
        - name: url
          value: $(params.config-repo-url)
      workspaces:
        - name: output
          workspace: config-source-workspace
        - name: ssh-directory
          workspace: config-git-creds
    - name: clone-source-repo
      runAfter:
        - debug-input
      taskRef: 
        name: git-clone
        kind: ClusterTask 
      params: 
        - name: url
          value: $(params.source-repo-url)
      workspaces:
        - name: output
          workspace: app-source-workspace
        - name: ssh-directory
          workspace: source-git-creds
    - name: kube-linter
      runAfter:
        - clone-config-repo
        - clone-source-repo
      taskRef:
        name: kube-linter
        kind: Task
      params:
        - name: manifest
          value: quarkus-super-heroes
        - name: includelist
          value: "no-extensions-v1beta,default-service-account,no-readiness-probe"
        - name: output_format
          value: "plain"
      workspaces:
        - name: source
          workspace: config-source-workspace
    - name: get-image-list
      runAfter:
        - kube-linter
      params:
        - name: change-id
          value: $(params.change-id)
      taskRef:
        kind: Task
        name: cms-get-images
    - name: deploy-integration
      params:
        - name: images
          value: $(tasks.get-image-list.results.image-list)
        - name: overlay-path
          value: sc-test
      taskRef:
        name: deploy-images
        kind: Task
      workspaces:
        - name: source
          workspace: config-source-workspace
      runAfter:
        - get-image-list
    - name: deploy-pst
      params:
        - name: images
          value: $(tasks.get-image-list.results.image-list)
        - name: overlay-path
          value: superheroes-pst
      taskRef:
        name: deploy-images
        kind: Task
      workspaces:
        - name: source
          workspace: config-source-workspace
      runAfter:
        - get-image-list
    - name: commit
      runAfter:
        - deploy-integration
        - deploy-pst
      taskRef:
        name: git-cli
        kind: ClusterTask
      params:
        - name: GIT_SCRIPT
          value: |
            cd $(workspaces.source.path)
            git add quarkus-super-heroes/overlays/superheroes-test/*
            git add quarkus-super-heroes/overlays/superheroes-pst/*
            git commit -m "Automatic updating images in superheroes-test overlay"
            git status
            git push origin HEAD:main
            sleep 30
        - name: GIT_USER_NAME
          value: CD Pipeline
        - name: GIT_USER_EMAIL
          value: invalid@redhat.com
      workspaces:
        - name: source
          workspace: config-source-workspace
        - name: ssh-directory
          workspace: source-git-creds
    - name: wait-integration
      params:
        - name: application
          value: superheroes-test
      taskRef:
        name: argocd-wait-for-deployment
        kind: Task
      runAfter:
        - commit
    - name: prep-tests
      params:
        - name: path
          value: integration-tests/pytest.ini
        - name: contents
          value: |
            [pytest]
            log_cli = true
            env =
                SEL_EP=http://selenium-hub-selenium-grid.apps.$(params.cluster-url)/wd/hub
                EVENT_EP=http://event-statistics-sc-test.apps.$(params.cluster-url)/
                FIGHT_EP=http://ui-super-heroes-sc-test.apps.$(params.cluster-url)/
        - name: mode
          value: '0644'
      runAfter:
        - wait-integration
      taskRef:
        kind: Task
        name: write-file
      workspaces:
        - name: output
          workspace: config-source-workspace
    - name: test-integration
      params:
        - name: PYTHON
          value: latest
        - name: ARGS
          value: '--log-cli-level=20 integration-tests/test.py --junitxml=/workspace/cms/integration-junitxml.xml'
        - name: SOURCE_PATH
          value: ./integration-tests/
        - name: REQUIREMENTS_FILE
          value: requirements.txt
      taskRef:
        kind: Task
        name: pytest
      workspaces:
        - name: source
          workspace: config-source-workspace
        - name: report-ws
          workspace: reports-workspace
      runAfter:
        - prep-tests
    - name: wait-pst
      params:
        - name: application
          value: superheroes-pst
      taskRef:
        name: argocd-wait-for-deployment
        kind: Task
      runAfter:
        - commit
    - name: test-pst
      params:
        - name: repo-url
          value: $(params.config-repo-url)
        - name: commit-id
          value: $(params.commit-id)
        - name: test-script
          value: k6-tests/load-test.js
        - name: endpoint-url
          value: rest-fights-superheroes-pst.apps.$(params.cluster-url)
      taskRef:
        kind: Task
        name: test-pst
      workspaces:
        - name: report-ws
          workspace: reports-workspace
        - name: code-ws
          workspace: config-source-workspace
      runAfter:
        - wait-pst
    - name: acs-scan-images
      taskRef:
        name: acs-image-scan
        kind: Task
      runAfter:
        - get-image-list
      params:
        - name: rox_central_endpoint
          value: rox-endpoint
        - name: rox_api_token
          value: rox-token
        - name: image-list
          value: $(tasks.get-image-list.results.image-list)
        - name: insecure-skip-tls-verify
          value: "true"
    - name: acs-check-results
      taskRef:
        name: acs-check-results
        kind: Task
      runAfter:
        - acs-scan-images
      params:
        - name: rox_central_endpoint
          value: rox-endpoint
        - name: rox_api_token
          value: rox-token
        - name: image-list
          value: $(tasks.get-image-list.results.image-list)
        - name: insecure-skip-tls-verify
          value: "true"
      workspaces:
        - name: report-ws
          workspace: reports-workspace
    - name: upload-cms
      params:
        - name: change-id
          value: $(params.change-id)
        - name: path-to-attach
          value: /workspace/cms
      taskRef:
        kind: Task
        name: cms-attach
      workspaces:
        - name: local-ws
          workspace: reports-workspace
      runAfter:
        - acs-check-results
        - test-integration
        - test-pst
    - name: update-cms
      params:
        - name: change-id
          value: $(params.change-id)
        - name: transition-id
          value: '15'
        - name: desired-status
          value: 'INTEGRATION_DEPLOYED'
      taskRef:
        kind: Task
        name: cms-transition-issue
      runAfter:
        - upload-cms
  workspaces:
    - name: reports-workspace
    - name: config-source-workspace
    - name: app-source-workspace
    - name: config-git-creds
    - name: source-git-creds
