apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: cd-deploytoprod
  name: el-cd-deploytoprod
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-cd-deploytoprod
    weight: 100
