apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: transform-secrets
  namespace: superheroes-build
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: transform-secrets
  namespace: superheroes-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: transform-secrets
subjects:
  - kind: ServiceAccount
    name: transform-secrets
    namespace: superheroes-build
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transform-secrets
  namespace: superheroes-build
