apiVersion: v1
kind: Secret
metadata:
  name: cms-secret
type: Opaque
data:
  auth-header: YkdWa1pYSmxjbVJBWjIxaGFXd3VZMjl0T21aQ1FUWkJabVZ6ZEVSSFltRjBhVFZGYTJ4R1FqZzFSZz09
  cms-url: aHR0cHM6Ly9zdW1tZXJjYW1wMjAyMy5hdGxhc3NpYW4ubmV0
