apiVersion: v1
kind: Secret
metadata:
  name: rox-endpoint
type: Opaque
data:
  rox_central_endpoint: Y2VudHJhbC1hY3MtaW5zdGFuY2UuYXBwcy5jbHVzdGVyLWdtNG53LmdtNG53LnNhbmRib3gzMDE2Lm9wZW50bGMuY29tOjQ0Mw==

