apiVersion: v1
kind: Secret
metadata:
  name: argo-secret
type: Opaque
data:
  auth-header: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKaGNtZHZZMlFpTENKemRXSWlPaUpoWkcxcGJqcHNiMmRwYmlJc0ltVjRjQ0k2TVRZM05EVTFPVEExTVN3aWJtSm1Jam94TmpjME5EY3lOalV4TENKcFlYUWlPakUyTnpRME56STJOVEVzSW1wMGFTSTZJakZoT1RWa05tRm1MVGMwWW1JdE5EWTNaaTFoTXpVekxXWm1OV0ZoT0RRNVptVXpOaUo5LmxURm1xWlZPNi04WmhGUnBOWlVkUjRxdmI3UE1wQ0dmdU5hemJyYXdPRTA=
  argo-url: aHR0cHM6Ly9vcGVuc2hpZnQtZ2l0b3BzLXNlcnZlci1vcGVuc2hpZnQtZ2l0b3BzLmFwcHMuY2x1c3Rlci00MmNoZC40MmNoZC5zYW5kYm94MTcxLm9wZW50bGMuY29t
