apiVersion: v1
kind: Secret
metadata:
  name: internal-registry
stringData:
  config.json: |
    {
      "auths": {
        "image-registry.openshift-image-registry.svc:5000": {
          "auth": "cmVndXNlcjpzaGEyNTZ+QUR2NjNzaGI0SnNIUHBVWkNUMDJQOFA5ZE8tUXRjazYyVi1BUkh2SXJyQQ=="
        }
      }
    }
