apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cd-deploytotest
spec:
  params:
    - name: change-id
    - name: commit-id
    - name: repo-url
    - name: images
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: cd-deploytotest
        name: cd-deploytotest-deploy-$(uid)
      spec:
        params:
          - name: change-id
            value: $(tt.params.change-id)
          - name: commit-id
            value: $(tt.params.commit-id)
          - name: source-repo-url
            value: $(tt.params.repo-url)
          - name: images
            value: $(tt.params.images)
        pipelineRef:
          name: cd-deploytotest
        workspaces:
          - name: reports-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                volumeMode: Filesystem
          - name: config-source-workspace
            persistentVolumeClaim:
              claimName: repo-code
          - name: app-source-workspace
            persistentVolumeClaim:
              claimName: maven-repo
          - name: config-git-creds
            secret:
              secretName: ssh-keys
          - name: source-git-creds
            secret:
              secretName: ssh-keys
