apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: cd-deploytoprod
spec:
  params:
    - name: change-id
      value: $(body.change-id)
    - name: commit-id
      value: $(body.commit-id)
    - name: repo-url
      value: $(body.repo-url)
    - name: images
      value: $(body.images)
