apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: selenium
  name: centos
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: docker.io/centos/s2i-base-centos7
      importPolicy: {}
      name: centos7
      referencePolicy:
        type: Source
