apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: selenium
    build: selenium-node-firefox-debug
  name: selenium-node-firefox-debug
spec:
  lookupPolicy:
    local: false
