apiVersion: v1
kind: Service
metadata:
  labels:
    app: selenium
  name: selenium-hub
spec:
  ports:
    - name: 4444-tcp
      port: 4444
      protocol: TCP
      targetPort: 4444
  selector:
    deploymentconfig: selenium-hub
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
