apiVersion: v1
kind: Secret
metadata:
  labels:
    app: rest-villains
    application: villains-service
    system: quarkus-super-heroes
  name: rest-villains-config-creds
data:
  quarkus.datasource.username: c3VwZXJiYWQ=
  quarkus.datasource.password: c3VwZXJiYWQ=
type: Opaque
---
