apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-linter.io/ignore-all: true
  labels:
    name: ui-super-heroes
    application: super-heroes
    system: quarkus-super-heroes
  name: ui-super-heroes
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: ui-super-heroes
    application: super-heroes
  type: ClusterIP
---
