apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "pvc-perftest-results"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem
