apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superheroes-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: superheroes-dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: quarkus-super-heroes/overlays/superheroes-dev
    repoURL: >-
      https://github.com/redhat-cbr/superheroes-cicd.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
