apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-security-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: acs-instance
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/advanced-cluster-security-operator/instance/overlays/default
    repoURL: >-
      https://github.com/redhat-cbr/superheroes-cicd.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}

