apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superheroes-pst
  namespace: openshift-gitops
spec:
  destination:
    namespace: superheroes-pst
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: quarkus-super-heroes/overlays/superheroes-pst
    repoURL: >-
      https://gitlab.consulting.redhat.com/anz-consulting/openshift/consulting-cop/summer-camp-2023.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers[]/image
