apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: openshift-gitops
spec:
  destination:
    namespace: sc-build
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: tekton
    repoURL: >-
      https://gitlab.consulting.redhat.com/anz-consulting/openshift/consulting-cop/summer-camp-2023.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true