apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selenium-grid
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: selenium-grid
    repoURL: https://www.selenium.dev/docker-selenium
    targetRevision: 0.15.0
    helm:
      releaseName: selenium-grid
      parameters:
      - name: "ingress.hostname"
        value: selenium-hub-selenium-grid.apps.cluster-9m4kt.9m4kt.sandbox539.opentlc.com
  destination:
    namespace: selenium-grid
    server: 'https://kubernetes.default.svc'
